config/routes.rb
FirstApp::Application.routes.draw do
  resources :first_appinfos
root :to => 'first_appinfos#index'

end

app/models/first_appinfo.rb
class FirstAppinfo < ActiveRecord::Base
  attr_accessible :email, :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/first_appinfos_controller.rb
class FirstAppinfosController < ApplicationController
  # GET /first_appinfos
  # GET /first_appinfos.json
  def index
    @first_appinfos = FirstAppinfo.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @first_appinfos }
    end
  end

  # GET /first_appinfos/1
  # GET /first_appinfos/1.json
  def show
    @first_appinfo = FirstAppinfo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @first_appinfo }
    end
  end

  # GET /first_appinfos/new
  # GET /first_appinfos/new.json
  def new
    @first_appinfo = FirstAppinfo.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @first_appinfo }
    end
  end

  # GET /first_appinfos/1/edit
  def edit
    @first_appinfo = FirstAppinfo.find(params[:id])
  end

  # POST /first_appinfos
  # POST /first_appinfos.json
  def create
    @first_appinfo = FirstAppinfo.new(params[:first_appinfo])

    respond_to do |format|
      if @first_appinfo.save
        format.html { redirect_to @first_appinfo, notice: 'First appinfo was successfully created.' }
        format.json { render json: @first_appinfo, status: :created, location: @first_appinfo }
      else
        format.html { render action: "new" }
        format.json { render json: @first_appinfo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /first_appinfos/1
  # PUT /first_appinfos/1.json
  def update
    @first_appinfo = FirstAppinfo.find(params[:id])

    respond_to do |format|
      if @first_appinfo.update_attributes(params[:first_appinfo])
        format.html { redirect_to @first_appinfo, notice: 'First appinfo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @first_appinfo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /first_appinfos/1
  # DELETE /first_appinfos/1.json
  def destroy
    @first_appinfo = FirstAppinfo.find(params[:id])
    @first_appinfo.destroy

    respond_to do |format|
      format.html { redirect_to first_appinfos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/first_appinfos_helper.rb
module FirstAppinfosHelper
end

app/views/first_appinfos/_form.html.erb
<%= form_for(@first_appinfo) do |f| %>
  <% if @first_appinfo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@first_appinfo.errors.count, "error") %> prohibited this first_appinfo from being saved:</h2>

      <ul>
      <% @first_appinfo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/first_appinfos/edit.html.erb
<h1>Editing first_appinfo</h1>

<%= render 'form' %>

<%= link_to 'Show', @first_appinfo %> |
<%= link_to 'Back', first_appinfos_path %>

app/views/first_appinfos/index.html.erb
<h1>Listing first_appinfos</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @first_appinfos.each do |first_appinfo| %>
  <tr>
    <td><%= first_appinfo.name %></td>
    <td><%= first_appinfo.email %></td>
    <td><%= link_to 'Show', first_appinfo %></td>
    <td><%= link_to 'Edit', edit_first_appinfo_path(first_appinfo) %></td>
    <td><%= link_to 'Destroy', first_appinfo, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New First appinfo', new_first_appinfo_path %>

app/views/first_appinfos/new.html.erb
<h1>New first_appinfo</h1>

<%= render 'form' %>

<%= link_to 'Back', first_appinfos_path %>

app/views/first_appinfos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @first_appinfo.name %>
</p>

<p>
  <b>Email:</b>
  <%= @first_appinfo.email %>
</p>


<%= link_to 'Edit', edit_first_appinfo_path(@first_appinfo) %> |
<%= link_to 'Back', first_appinfos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FirstApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>